import type { Metadata } from 'next';
import { Inter } from 'next/font/google';
import './globals.css';
import RequireAuth from '@/components/requireAuth';

const inter = Inter({ subsets: ['latin'] });

export const metadata: Metadata = {
  title: 'Farm Origins',
  description: 'Generated by create next app'
};

export default function RootLayout({
  children
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <RequireAuth> {children}</RequireAuth>
      </body>
    </html>
  );
}
